In [1]:
!python --version

Python 3.11.11


In [2]:
import numpy as np
np.__version__

'1.26.4'

In [ ]:
#link to Machine learning databases https://archive.ics.uci.edu/ml
# Learning Numpy and Pandas today

In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

#load Iris dataset
url='https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
col_names = ['sep_len','sep_wid','pet_len','pet_wid','species']
iris_df = pd.read_csv(url,names=col_names)

In [4]:
iris_df

sep_len  sep_wid  pet_len  pet_wid         species
0        5.1      3.5      1.4      0.2     Iris-setosa
1        4.9      3.0      1.4      0.2     Iris-setosa
2        4.7      3.2      1.3      0.2     Iris-setosa
3        4.6      3.1      1.5      0.2     Iris-setosa
4        5.0      3.6      1.4      0.2     Iris-setosa
..       ...      ...      ...      ...             ...
145      6.7      3.0      5.2      2.3  Iris-virginica
146      6.3      2.5      5.0      1.9  Iris-virginica
147      6.5      3.0      5.2      2.0  Iris-virginica
148      6.2      3.4      5.4      2.3  Iris-virginica
149      5.9      3.0      5.1      1.8  Iris-virginica

[150 rows x 5 columns]

In [12]:
iris_df.columns
#iris_df.attrs

Index(['sep_len', 'sep_wid', 'pet_len', 'pet_wid', 'species'], dtype='object')

In [10]:
iris_df['species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

**Numpy**

In [18]:
ary_1d = np.array([1,2,3,4,5,6])
ary_2d = np.array([[1,2,3],[4,5,6],[7,8,9]]) #Matrix
print("1D Array \n",ary_1d)
print("2D Arry \n",ary_2d)

1D Array 
 [1 2 3 4 5 6]
2D Arry 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
# properties of array
print('Shape of arry', ary_2d.shape)
print('Data type of the arry ', ary_2d.dtype)
print('Number of dimensions ',ary_2d.ndim)

print("Shape ",ary_1d.shape)
print("number of dimensions ",ary_1d.ndim)

Shape of arry (3, 3)
Data type of the arry  int64
Number of dimensions  2
Shape  (6,)
number of dimensions  1


In [27]:
#3D array
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]],dtype='int32')
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [29]:
arr.dtype
print("Dimensions ",arr.ndim)

Dimensions  3


In [31]:
print("First row of 2d arry ", ary_2d[0,:])
print("First column of 2d arry ", ary_2d[:,0])

First row of 2d arry  [1 2 3]
First column of 2d arry  [1 4 7]


In [36]:
print("First row of 3d arry ", arr[0,:,:])
print("middle column of 3d arry ", arr[:,:,0])

First row of 3d arry  [[1 2 3]
 [4 5 6]]
middle column of 3d arry  [[1 4]
 [1 4]]


In [58]:
#Generating matrix
flt_ary = np.arange(1.5,28,dtype='float64').reshape(3,3,-1)
print(flt_ary)

[[[ 1.5  2.5  3.5]
  [ 4.5  5.5  6.5]
  [ 7.5  8.5  9.5]]

 [[10.5 11.5 12.5]
  [13.5 14.5 15.5]
  [16.5 17.5 18.5]]

 [[19.5 20.5 21.5]
  [22.5 23.5 24.5]
  [25.5 26.5 27.5]]]
